# Generated by Django 5.1.3 on 2024-12-04 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='otp_created_at',
            new_name='otp_expiry',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='otp_max_try_started_from',
            new_name='otp_max_try_expiry',
        ),
    ]
