# Generated by Django 5.1.3 on 2024-12-06 10:33

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_otp_created_at_customuser_otp_expiry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_attemps', models.PositiveIntegerField(default=1)),
                ('otp_expiry', models.DateTimeField(default=accounts.models.OTPRequest.default_otp_expiry)),
                ('otp_attemps_expiry', models.DateTimeField(default=accounts.models.OTPRequest.default_otp_attemps_expiry)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='otp_code',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='otp_expiry',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='otp_max_try_expiry',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='otp_trys',
        ),
    ]
