# Generated by Django 5.1.3 on 2024-12-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_otprequest_remove_customuser_otp_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='otp_attemps',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
