# Generated by Django 5.1.3 on 2024-12-07 13:17

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_otprequest_otp_attemps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='otp_attemps_expiry',
            field=models.DateTimeField(blank=True, default=accounts.models.OTPRequest.default_otp_attemps_expiry, null=True),
        ),
        migrations.AlterField(
            model_name='otprequest',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, default=accounts.models.OTPRequest.default_otp_expiry, null=True),
        ),
    ]
