# Generated by Django 5.1.3 on 2024-12-08 11:00

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_otprequest_otp_attemps_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='otp_attemps_expiry',
            field=models.DateTimeField(default=accounts.models.OTPRequest.default_otp_attemps_expiry),
        ),
        migrations.AlterField(
            model_name='otprequest',
            name='otp_expiry',
            field=models.DateTimeField(default=accounts.models.OTPRequest.default_otp_expiry),
        ),
    ]
